### ISSUE TITLE
graql command not recognized + excepetion error 'action_query_entities'

### ISSUE THREAD

**Issue by WR1171** [RasaHQ/tutorial-knowledge-base#1]
After I train, rasa actions server, and rasa shell I get this error after a few lines of dialogue, I say hello, bot replies "I can give you some info......", I ask 

"Can you give me information on my account please"

I get;

 Encountered an exception while running action 'action_query_entities'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code

When first building the bot;

When I get to this command:

graql console --keyspace banking --file knowledge_base/schema.gql

I get no command found, but I can change the graql to grakn and it works?

I've installed grakn, run the server no problem, when I run; python knowledge_base/migrate.py 

I get some errors, listed below 

james:~/know# python knowledge_base/migrate.py
Loading data from [./knowledge_base/data/person] into Grakn ...
Traceback (most recent call last):
  File "/root/miniconda3/envs/rasabot/lib/python3.6/site-packages/grakn/service/Session/TransactionService.py", line 145, in send
    response = next(self._response_iterator)
  File "/root/miniconda3/envs/rasabot/lib/python3.6/site-packages/grpc/_channel.py", line 364, in __next__
    return self._next()
  File "/root/miniconda3/envs/rasabot/lib/python3.6/site-packages/grpc/_channel.py", line 358, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "null. Please check server logs for the stack trace."
        debug_error_string = "{"created":"@1563228826.113574006","description":"Error received from peer ipv4:127.0.0.1:48555","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"null. Please check server logs for the stack trace.","grpc_status":2}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "knowledge_base/migrate.py", line 201, in <module>
    build_banking_graph(inputs)
  File "knowledge_base/migrate.py", line 10, in build_banking_graph
    load_data_into_grakn(input, session)
  File "knowledge_base/migrate.py", line 17, in load_data_into_grakn
    with session.transaction(grakn.TxType.WRITE) as tx:
  File "/root/miniconda3/envs/rasabot/lib/python3.6/site-packages/grakn/__init__.py", line 69, in transaction
    transaction_service = TransactionService(self.keyspace, tx_type, self.credentials, self._stub.transaction)
  File "/root/miniconda3/envs/rasabot/lib/python3.6/site-packages/grakn/service/Session/TransactionService.py", line 39, in __init__
    self._communicator.send(open_req)
  File "/root/miniconda3/envs/rasabot/lib/python3.6/site-packages/grakn/service/Session/TransactionService.py", line 149, in send
    raise GraknError("Server/network error: {0}\n\n generated from request: {1}".format(e, request))
grakn.exception.GraknError.GraknError: Server/network error: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "null. Please check server logs for the stack trace."
        debug_error_string = "{"created":"@1563228826.113574006","description":"Error received from peer ipv4:127.0.0.1:48555","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"null. Please check server logs for the stack trace.","grpc_status":2}"
>

 generated from request: open_req {
  keyspace: "banking"
  type: WRITE

**Comment by tabergma** [comment]
@WR1171 Thanks for trying the bot! :) Did you start the grakn server with `grakn server start`? It looks like grakn is not running.

**Comment by WR1171** [comment]
Thanks for the fast reply!  Rasa has been interesting since the X came out, with new labeling etc!!

I did start the Grakn server, when I went down a few possible problems(?) I found that Grakn client wasn't installed after looking up some of the errors. 

I found this

https://discuss.grakn.ai/t/phone-calls-example-incompatible-with-1-5-2/1202

With similar errors, I didn't have client even installed, so that fixed one of the errors I was facing, but I cannot get the graql command to work at all.  Everytime I attempt to use it I get, No command.

So now that I have client python installed when I run the migrate.py script, it looks like it works I get 

james:~/know# python knowledge_base/migrate.py
Traceback (most recent call last):
  File "knowledge_base/migrate.py", line 201, in <module>
    build_banking_graph(inputs)
  File "knowledge_base/migrate.py", line 6, in build_banking_graph
    client = grakn.Grakn(uri="localhost:48555")
AttributeError: module 'grakn' has no attribute 'Grakn'

When I run rasa shell and talk to the bot I still get this error after I say hi, the bot follows up, I ask anything I get

Encountered an exception while running action 'action_query_entities'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.

Actions server running, Grakn running? Help!!

Thanks!

**Comment by tabergma** [comment]
It seems like you have a newer version of grakn installed. You need to have grakn version 1.4.2. installed. Can you please check what version you are using?

**Comment by WR1171** [comment]
Yup! I am using the latest grakn and I have no idea how to install 1.4.2, the links you have listed bring you how to install the latest version and not 1.4.2 - When I go to download the version and compile myself their Linux zip they offer looks like its windows and not linux.  

Not sure how to install grakn 1.4.2?

**Comment by tabergma** [comment]
I just updated the code to use grakn 1.5.7. Can you please try again?

**Comment by tabergma** [comment]
@WR1171 Is it working for you now? If yes, I would like to close this issue. Thanks.

**Comment by WR1171** [comment]
Great! I was out of town on travel, haven't tried, but I think this will probably work now.  I couldn't find the correct grakn and how to install it so I actually gave up.  Now that the newer version is working I will follow and try, but I am sure it will work now. Cheers!
