### ISSUE TITLE
Update lookuptables

### ISSUE THREAD

**Issue by chikubee** [RasaHQ/tutorial-knowledge-base#13]
I see reference to lookup lists are used in the training samples for query_kb intents.
Talking with reference to the banking demo, 
does this imply every time an entry is made to the kb like a person / bank, it needs to be added in this list and model has to be retrained?

**Comment by sara-tagger** [comment]
Thanks for the issue, @degiz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by degiz** [comment]
@tabergma could you please comment?

**Comment by tabergma** [comment]
@chikubee Not necessarily. The model should be able to recognize most person/bank entities without adding them to the lookup tables. However, if you recognize that your model is not recognizing a specific person/bank, it might help to add it to the lookup table and retrain the model. Whenever you add something to the lookup table it will be converted into a new feature during training indicating that the word matches a value of the particular lookup table, which is a good indication for the model to label a word as a specific entity. However, as the model as access to a lot of more features, it might also be able to recognize the person/bank without the extra feature. Hope that helps.
