### ISSUE TITLE
migrating error 

### ISSUE THREAD

**Issue by Eranga-sof** [RasaHQ/tutorial-knowledge-base#7]
I got the error when I migrating could you help me soon please,

Loading from [./knowledge_base/data/person] into Grakn ...
Traceback (most recent call last):
  File "E:\Projects\KB\tutorial-knowledge-base-master\knowledge_base\migrate.py", line 201, in <module>
    build_banking_graph(inputs)
  File "E:\Projects\KB\tutorial-knowledge-base-master\knowledge_base\migrate.py", line 10, in build_banking_graph
    load_data_into_grakn(input, session)
  File "E:\Projects\KB\tutorial-knowledge-base-master\knowledge_base\migrate.py", line 14, in load_data_into_grakn
    items = parse_data_to_dictionaries(input)
  File "E:\Projects\KB\tutorial-knowledge-base-master\knowledge_base\migrate.py", line 165, in parse_data_to_dictionaries
    with open(input["data_path"] + ".csv") as data:  # 1
FileNotFoundError: [Errno 2] No such file or directory: './knowledge_base/data/person.csv'

**Comment by Eranga-sof** [comment]
I migrated successfully. after clear all grkan and then I re migrate the models.

**Comment by siddharthchauhan** [comment]
> I migrated successfully. after clear all grkan and then I re migrate the models.

Can you please tell how you solved this issue?
I am getting the same issue.

**Comment by Eranga-sof** [comment]
Did you execute all command in grakn

**Comment by siddharthchauhan** [comment]
> Did you execute all command in grakn
> […](#)
> On Mon, 2 Mar 2020, 11:28 am Siddharth, ***@***.***> wrote: I migrated successfully. after clear all grkan and then I re migrate the models. Can you please tell how you solved this issue? I am getting the same issue. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub <#7?

Yes

**Comment by Eranga-sof** [comment]
When you run this command.

python knowledge_base/migrate.py

You open cmd outside the knwladge-base folder thats reason we got
error.good luck

**Comment by siddharthchauhan** [comment]
No, I opened inside only.

**Comment by Eranga-sof** [comment]
No try in outside because inside have file path. thats match when you run
in outside

**Comment by siddharthchauhan** [comment]
can you give example? I am not really getting it.

**Comment by Eranga-sof** [comment]
Wait brother

**Comment by Eranga-sof** [comment]
try open in this file path

**Comment by Eranga-sof** [comment]
After execute grakn code you run this command. that file path, which as i
sent photos

python knowledge_base/migrate.py

**Comment by siddharthchauhan** [comment]
i dont see pictures.

**Comment by Eranga-sof** [comment]
Like this

**Comment by siddharthchauhan** [comment]
Bro, I cant see anything.
<img width="976" alt="Screen Shot 2020-03-02 at 10 00 41 PM" src="https://user-images.githubusercontent.com/12405488/75696228-43954e00-5cd1-11ea-8c4c-dad16950047c.png">

**Comment by Eranga-sof** [comment]
Can  you send mail erangabuddika33@gmail.com

**Comment by siddharthchauhan** [comment]
Please send me your screenshot email on siddharthc96@gmail.com.
