### ISSUE TITLE
python migrate.py error

### ISSUE THREAD

**Issue by siddharthchauhan** [RasaHQ/tutorial-knowledge-base#8]
(rasa) PS C:\Users\siddharth.chauhan\AppData\Local\Continuum\anaconda3\envs\rasa\Projects\POC_knowledge_base\knowledge_base> python migrate.py
Loading from [./knowledge_base/data/person] into Grakn ...
Traceback (most recent call last):
  File "migrate.py", line 201, in <module>
    build_banking_graph(inputs)
  File "migrate.py", line 10, in build_banking_graph
    load_data_into_grakn(input, session)
  File "migrate.py", line 14, in load_data_into_grakn
    items = parse_data_to_dictionaries(input)
  File "migrate.py", line 165, in parse_data_to_dictionaries
    with open(input["data_path"] + ".csv") as data:  # 1
FileNotFoundError: [Errno 2] No such file or directory: './knowledge_base/data/person.csv'

**Comment by tabergma** [comment]
@siddharthchauhan Did you fix the error? I guess you are missing the `person.csv` file. You need it to insert some person data into your knowledge base.

**Comment by sumyatthitsarr** [comment]
@siddharthchauhan Actually you should run outside the knowledge_base folder.
please use `python knowledge_base/migrate.py`
